apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: my-cronjob
        spec:
          containers:
          - name: worker
            image: busybox:1.36
            command: ['sh', '-c', 'echo "CronJob executed at $(date)"; sleep 10']
          restartPolicy: OnFailure
